// Generated by CoffeeScript 1.9.2
(function() {
  $(function() {
    $('.unlink').on('click', function() {
      var file;
      if (window.confirm('削除しますか?')) {
        file = $(this);
        return $.ajax({
          method: 'post',
          url: '/api/unlink.json',
          data: {
            path: file.attr('name')
          }
        }).done(function() {
          return file.parent().remove();
        });
      }
    });
    $('#mkdir').on('click', function() {
      return $.ajax({
        method: 'post',
        url: '/api/mkdir.json',
        data: {
          dir: $('head > title').text() + $('#dir-name').val()
        }
      }).done(function(data) {
        return location.href = './';
      }).error(function(data) {
        return alert(JSON.stringify(data));
      });
    });
    return $('form').submit(function() {
      $('#mkdir').click();
      return false;
    });
  });

}).call(this);

//# sourceMappingURL=explorer.js.map
