// Generated by CoffeeScript 1.9.2
(function() {
  var cancelEvent;

  window.qualia = {};

  (function() {
    if (typeof Notification !== "undefined" && Notification !== null) {
      Notification.requestPermission(function(status) {
        if (Notification.permission !== status) {
          return Notification.permission = status;
        }
      });
    }
    window.WebNotify = function(title, body, icon, timeout) {
      var n, ref, ref1;
      if ((ref = document.querySelector('#sound')) != null) {
        ref.load();
      }
      if ((ref1 = document.querySelector('#sound')) != null) {
        ref1.play();
      }
      n = typeof Notification === "function" ? new Notification(title, {
        body: body,
        icon: icon
      }) : void 0;
      return setTimeout(function() {
        return n != null ? n.close() : void 0;
      }, timeout);
    };
    return window.qualia.notify = function(status) {
      return WebNotify('Info', status, '/icon/info.png', 2000);
    };
  }).call(this);

  cancelEvent = function(event) {
    event.preventDefault();
    return event.stopPropagation();
  };

  $('html').on('dragenter', cancelEvent).on('dragover', cancelEvent).on('drop', cancelEvent);

  window.qualia.set_background_function = function(target_element) {
    target_element = $('body');
    $('html').on('drop', function(event) {
      var file, reader, ref, target;
      file = (ref = event.originalEvent.dataTransfer.files) != null ? ref[0] : void 0;
      if (!file) {
        return;
      }
      if (!file.name.match(/^.*.(jpg|png)/)) {
        return alert('背景はPNG/JPGしか設定できません!');
      }
      target = $(this);
      reader = new FileReader();
      reader.onload = function(e) {
        var img;
        img = e.target.result;
        localStorage.background = img;
        return target_element.css({
          'background': 'url("' + img + '")',
          'background-size': 'cover',
          'background-attachment': 'fixed'
        });
      };
      return reader.readAsDataURL(file);
    });
    if (localStorage.background) {
      return target_element.css({
        'background': 'url("' + localStorage.background + '")',
        'background-size': 'cover',
        'background-attachment': 'fixed'
      });
    }
  };

  $(function() {
    shortcut.add('Ctrl+Z', function() {
      if (localStorage.background) {
        localStorage.removeItem('background');
        qualia.notify('背景画像を削除しました');
        return location.href = location.href;
      }
    });
    shortcut.add('Ctrl+Space', function() {
      return location.href = '/';
    });
    return shortcut.add('Ctrl+A', function() {
      if (localStorage.href === location.href) {
        localStorage.removeItem('href');
        return qualia.notify('開いているページの記録を削除しました');
      } else {
        localStorage.href = location.href;
        return qualia.notify('開いてるページの記憶を設定しました!');
      }
    });
  });

  if (localStorage.href) {
    if (location.href !== localStorage.href) {
      if (confirm(localStorage.href + ' が記憶されています、開きますか?')) {
        location.href = localStorage.href;
      }
    }
  }

  window.qualia.upload = function(file, name, path, progress, done, error) {
    var fd;
    fd = new FormData();
    fd.append('filename', name.replace(/([\/\\<>~|])/g, '_'));
    fd.append('path', path.replace(/\//g, '\\'));
    fd.append('file', file);
    return $.ajax({
      async: true,
      xhr: function() {
        var XHR;
        XHR = $.ajaxSettings.xhr();
        if (XHR.upload) {
          XHR.upload.addEventListener('progress', function(e) {
            return typeof progress === "function" ? progress(parseInt(e.loaded / e.total * 10000) / 100) : void 0;
          });
        }
        return XHR;
      },
      method: 'post',
      url: '/api/upload.json',
      data: fd,
      processData: false,
      contentType: false
    }).done(done).error(error);
  };

  $(function() {
    var span;
    span = $(document.createElement('sapn'));
    span.css({
      'position': 'fixed',
      'display': 'block',
      'right': '0',
      'bottom': '0',
      'background': 'url("/img/qualia.png")',
      'background-size': 'cover',
      'width': '150px',
      'height': '50px',
      'z-index': '0'
    });
    return $(document.body).append(span);
  });

}).call(this);

//# sourceMappingURL=qualia.js.map
